name = "run-jobscraper"
main = "src/index.js"
compatibility_date = "2024-08-02"

[triggers]
crons = ["55 5-19/2 * * SUN-THU", "55 5-15/2 * * FRI"]

[observability]
enabled = true
head_sampling_rate = 1