name = "run-jobscraper"
main = "src/index.js"
compatibility_date = "2024-08-02"

[triggers]
crons = ["55 4-18/2 * * SUN-THU", "55 4-14/2 * * FRI"]

[observability]
enabled = true
head_sampling_rate = 1