name = "run-jobscraper"
main = "src/index.js"
compatibility_date = "2024-08-02"

[triggers]
crons = ["54 4,6,8,10,12,14,16,18 * * 0-4", "54 4,6,8,10,12,14 * * 5"]

[observability]
enabled = true
head_sampling_rate = 1